#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ryusei Matsuki
# SPDX-License-Identifier: BSD-3-Clause

def prime_factorization(n):
    factors = []
    
    while n % 2 == 0:
        factors.append(2)
        n = n // 2
    
    for i in range(3, int(n**0.5) + 1, 2):
        while n % i == 0:
            factors.append(i)
            n = n // i
    
    if n > 2:
        factors.append(n)
    
    return factors

num = int(input(" "))

result = prime_factorization(num)

print(f"{num} の素因数分解結果: {result}")

